### ISSUE TITLE
I'm getting an error

### ISSUE THREAD

**Issue by Luoboawa** [RRS-9747/HeadDrop#35]
[12:29:57 ERROR]: Could not pass event EntityDeathEvent to HeadDrop v4.34
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at [H][头颅]HeadDrop-5.2.1.jar/me.rrs.lib.nbtapi.utils.MinecraftVersion.getVersion(MinecraftVersion.java:111) ~[[H][头颅]HeadDrop-5.2.1.jar:?]
        at [H][头颅]HeadDrop-5.2.1.jar/me.rrs.lib.nbtapi.NBTCompound.getType(NBTCompound.java:1342) ~[[H][头颅]HeadDrop-5.2.1.jar:?]
        at [H][头颅]HeadDrop-5.2.1.jar/me.rrs.lib.nbtapi.NBTCompound.addCompound(NBTCompound.java:765) ~[[H][头颅]HeadDrop-5.2.1.jar:?]
        at [H][头颅]HeadDrop-5.2.1.jar/me.rrs.headdrop.util.ItemUtils.rename(ItemUtils.java:17) ~[[H][头颅]HeadDrop-5.2.1.jar:?]
        at [H][头颅]HeadDrop-5.2.1.jar/me.rrs.headdrop.database.EntityHead.getSkull(EntityHead.java:214) ~[[H][头颅]HeadDrop-5.2.1.jar:?]
        at [H][头颅]HeadDrop-5.2.1.jar/me.rrs.headdrop.listener.EntityDeath.entityDropHeadEvent(EntityDeath.java:2134) ~[[H][头颅]HeadDrop-5.2.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor147.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-DEV-791d374]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:56) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:998) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1909) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1812) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1617) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1344) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2930) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.onAttack(ServerGamePacketListenerImpl.java:2945) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:29) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2856) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:76) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:14) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:58) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$2(PacketUtils.java:86) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:181) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1711) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:459) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:546) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by RRS-9747** [comment]
Use latest version
