### ISSUE TITLE
Error on latest paper version

### ISSUE THREAD

**Issue by shantek** [RRS-9747/HeadDrop#36]
When running the latest version of paper, on an entity death I get the following error:

[13:21:31 ERROR]: Could not pass event EntityDeathEvent to HeadDrop v5.2.1
java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile
        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228) ~[?:?]
        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115) ~[?:?]
        at java.base/java.lang.reflect.Field.set(Field.java:836) ~[?:?]
        at HeadDrop.jar/me.rrs.headdrop.util.SkullCreator.mutateItemMeta(SkullCreator.java:90) ~[HeadDrop.jar:?]
        at HeadDrop.jar/me.rrs.headdrop.util.SkullCreator.itemWithBase64(SkullCreator.java:55) ~[HeadDrop.jar:?]
        at HeadDrop.jar/me.rrs.headdrop.util.SkullCreator.createSkullWithBase64(SkullCreator.java:32) ~[HeadDrop.jar:?]
        at HeadDrop.jar/me.rrs.headdrop.database.EntityHead.getSkull(EntityHead.java:203) ~[HeadDrop.jar:?]
        at HeadDrop.jar/me.rrs.headdrop.listener.EntityDeath.lambda$populateEntityActions$28(EntityDeath.java:575) ~[HeadDrop.jar:?]
        at HeadDrop.jar/me.rrs.headdrop.listener.EntityDeath.entityDropHeadEvent(EntityDeath.java:150) ~[HeadDrop.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor667.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2324-e12a4de]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:1007) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1957) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1858) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1651) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1383) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2544) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$4.onAttack(ServerGamePacketListenerImpl.java:2961) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:29) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2870) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:76) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:14) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1517) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1362) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by makegodhere** [comment]
Me too

**Comment by RRS-9747** [comment]
Fixed on latest HeadDrop-Premium. The free version will get the update soon
